#配置ddl的参数
spring.jpa:
     #databasePlatform: org.hibernate.dialect.H2Dialect
     databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect  #mysql
     show-sql: true
     hibernate.ddl-auto: update


#Spring data jpa默认使用H2数据库，因此不需要额外指定驱动等信息，
#但是如果使用Mysql等数据库，则需要如下配置
#1.在类路径添加Mysql驱动包
#2.在application.yml配置连接参数

spring.datasource: 
  url: jdbc:mysql://119.29.223.108:60330/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
  username: dev
  password: 1q2w#E$R
  #type: com.zaxxer.hikari.HikariDataSource #指定连接池为Hikari，默认使用Tocamt连接池
  driver-class-name: com.mysql.jdbc.Driver #也可以不指定，springboot根据url自动识别